---
title: "Practice RMarkdown"
author: "Emelia J Chamberlain"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
```

## Introduction

Here we will be analyzing a biogeochemical data set collected from the central Arctic Ocean, near the north pole collected in April or May from 2000-2014.

Data downloaded from ADC via [link.](https://arcticdata.io/catalog/view/doi:10.18739/A25T3FZ8X)

### Read Data

```{r}
bg_chem <- read_csv("data/BGchem2008data.csv")
```

```{r exploration, echo = FALSE, eval = FALSE}
colnames(bg_chem)
str(bg_chem)
head(bg_chem)
```

## Analysis

### Calculate summary statistics

```{r stats}
nitrate <- mean(bg_chem$NO3)
nitrite <- mean(bg_chem$NO2)
amm <- mean(bg_chem$NH4)
phos <- mean(bg_chem$P)
```

### Calculate mean Redfield ratio

```{r ratio}
ratio <- (nitrate + nitrite + amm)/phos
```

The Redfield ratio in this data set is approximately `r round(ratio)`

### Plot Redfield Ratio
```{r plotting, echo = FALSE}
plot(bg_chem$P, bg_chem$NO2 + bg_chem$NO3 + bg_chem$NH4)
```


